### ISSUE TITLE
Switch icon's color doesn't change based on state 

### ISSUE THREAD

**Issue by Warter21** [thomasloven/lovelace-fold-entity-row#149] opened 2021-04-05 17:54 UTC
My Home Assistant version: 2021.3.4

Fold-entity-row version (FROM BROWSER CONSOLE):
latest

What I am doing:
type: entities
entities:
  - type: 'custom:fold-entity-row'
    head: switch.tpsp01
    padding: 0
    entities:
      - type: divider
      - sensor.tpsp01_amps
      - sensor.tpsp01_volts
      - sensor.tpsp01_watts
      - sensor.tpsp01_today_kwh
      - sensor.tpsp01_total_kwh
state_color: true

What I expected to happen:
change the color based on the state

What happened instead:
color doesn't change

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment] 2021-04-05 18:14
Duplicate of #133

**Closed by thomasloven** 2021-04-05 18:14 UTC
