### ISSUE TITLE
Open template

### ISSUE THREAD

**Issue by danb5** [thomasloven/lovelace-fold-entity-row#117] opened 2020-07-23 10:43 UTC
Is it possible to use an If statement to have the card open if something is on? For example: The card is set to be closed unless any entity is on or open in which case the card will be open?

**Comment by david-kalbermatten** [comment] 2020-07-23 21:37
yea, having a `value_template` would be awesome. This way you could define the card to be open when a certain device or sensor is on...

**Comment by thomasloven** [comment] 2021-02-26 15:13
Duplicate of #60

**Closed by thomasloven** 2021-02-26 15:13 UTC
