### ISSUE TITLE
Label without section line

### ISSUE THREAD

**Issue by kloggy** [thomasloven/lovelace-fold-entity-row#83] opened 2020-01-28 12:25 UTC
Would it be possible to have the `head` consist of just a label?
i.e. Exactly as you have in your examples but without the dividing line.

So instead of:
![image](https://user-images.githubusercontent.com/38220016/73263689-08cb6200-41c9-11ea-9af3-036fd72199bc.png)

We could have this:
![image](https://user-images.githubusercontent.com/38220016/73263740-2bf61180-41c9-11ea-91b8-35dbefb7fb0c.png)

**Comment by thomasloven** [comment] 2020-01-28 14:12
Duplicate of #81

**Closed by thomasloven** 2020-01-28 14:12 UTC
