### ISSUE TITLE
Head options broken

### ISSUE THREAD

**Issue by Justahobby01** [thomasloven/lovelace-fold-entity-row#95] opened 2020-03-22 16:53 UTC
My Home Assistant version: 0.107.5

Using type and label beneath the head now results in an error.

This no longer works:

          - type: custom:fold-entity-row
            head: 
              type: section
              label: Roomba Stats
            group_config:
              secondary_info: last-changed
            entities: 
             - entity: sensor.roomba_battery
             - entity: sensor.roomba_status
           

![Screenshot_20200322-114923__01](https://user-images.githubusercontent.com/44276845/77255173-8b095d00-6c33-11ea-8eff-2a167d2e8de5.jpg)

However, this still works:

         - type: custom:fold-entity-row
            head: sensor.battery_charger_watts
            group_config:
              secondary_info: last-changed
            entities:

**Comment by thomasloven** [comment] 2020-03-23 15:14
Duplicate of #91 and #93 .
Duplicate of #94?

**Closed by thomasloven** 2020-03-23 15:15 UTC
