### ISSUE TITLE
errors in chrome dev console

### ISSUE THREAD

**Issue by vMeph** [thomasloven/lovelace-fold-entity-row#218] opened 2022-03-05 20:39 UTC
My Home Assistant version: 2022.3.1

Fold-entity-row version (FROM BROWSER CONSOLE):

`slider-entity-row.js?hacstag=1448997001721:1 The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'. See https://lit.dev/msg/deprecated-import-path for more information.`

**Comment by thomasloven** [comment] 2022-03-05 20:56
Duplicate of thomasloven/lovelace-slider-entity-row#228 ... you know... on the **slider-entity-row** repo... seing as it says "slider-entity-row" in the... you get it.

:wink:

**Closed by thomasloven** 2022-03-05 20:56 UTC
