### ISSUE TITLE
tapable

### ISSUE THREAD

**Issue by NemesisRE** [thomasloven/lovelace-fold-entity-row#157] opened 2021-05-21 01:17 UTC
First of all your extensions are absolutely great!

Could be just my setup, but I like to fold some cards by default and just open the fold with a click or tap.
If I enable clickable this works perfect at a PC but doesn't on mobile devices.

If this is not just an issue in my setup I would like to have something like tabable and when you set tabable secondary info should automatically move to the hold_action.

kind regards
Steven

**Comment by thomasloven** [comment] 2021-06-29 22:47
Duplicate of the correctly filed #167

**Closed by thomasloven** 2021-06-29 22:47 UTC
Labels: enhancement
